{
  "arrowParens": avoid,
  "bracketSpacing": true,
  "endOfLine": "lf",
  "importOrder": ["module-alias/register", "<THIRD_PARTY_MODULES>", "^[./]"],
  "importOrderParserPlugins": ["typescript"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true,
  "printWidth": 120,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": all,
  "overrides": [{ "files": "*.sol", "options": { "tabWidth": 4 } }],
}
