name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  PRIVATE_KEY: 4433d156e8c53bf5b50af07aa95a29436f29a94e0ccc5d58df8e57bdc8583c32
  INFURA_API_KEY: INFURA_API_KEY
  YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        # Hack to get around failing "ethereumjs-abi The remote archive doesn't match the expected checksum" error
        run: YARN_CHECKSUM_BEHAVIOR=update yarn

      - name: Lint soliditidy and ts files
        run: yarn lint

  test:
      name: Test
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]

      steps:
        - name: Check out code
          uses: actions/checkout@v2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: "yarn"

        - name: Install dependencies
          # Hack to get around failing "ethereumjs-abi The remote archive doesn't match the expected checksum" error
          run: YARN_CHECKSUM_BEHAVIOR=update yarn

        - name: Test
          run: yarn test
